name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-with-gradle-build-action-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
      - uses: gradle/gradle-build-action@v2
        name: Gradle bootBuildImage and publish
        with:
          arguments: bootBuildImage --publishImage
        env:
          ORG_GRADLE_PROJECT_DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          ORG_GRADLE_PROJECT_DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
